// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVLwAW984V9-bxGhsh0bUUJBPUxUyPhM',
    appId: '1:109799530750:android:1f14fcf8d98c8f8d5dc5af',
    messagingSenderId: '109799530750',
    projectId: 'gamedevapp-83495',
    storageBucket: 'gamedevapp-83495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNVmOkWI1YZS-EFsoaPCjWIODFM5H7W8',
    appId: '1:109799530750:ios:cc4af09e9516d3c25dc5af',
    messagingSenderId: '109799530750',
    projectId: 'gamedevapp-83495',
    storageBucket: 'gamedevapp-83495.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChnv0kPbDRA4pKlxbZLMjT62PyDXVnG1k',
    appId: '1:109799530750:web:df7a2140905753205dc5af',
    messagingSenderId: '109799530750',
    projectId: 'gamedevapp-83495',
    authDomain: 'gamedevapp-83495.firebaseapp.com',
    storageBucket: 'gamedevapp-83495.firebasestorage.app',
    measurementId: 'G-4X5YL9HQE2',
  );

}